### ISSUE TITLE
Unmaintainable README-language.md

### ISSUE THREAD

**Issue by Raff-dev** [OpenBMB/ChatDev#180]
Having a readme for every language is simply unmaintainable - every time a readme is updated, it would need to be updated in every file, whereas I, for instance, don't know all the languages for which `README.md` exist in this repo :p. 

I see two approaches that could be taken here:
- keep only the English version of the README.md file
- automate translation of the README.md file

The automation could even be accomplished  in a GitHub workflow that would send a request to GPT API if README.md was changed and commit the newly created files for other languages.

Nevertheless, is it necessary to have the readmes in any other language than English? There are browser extensions that allow translation of the website content, so I don't think individual users would have a problem with that.

Hence, I suggest to keep only the English version of `README.md `

**Comment by ManindraDeMel** [comment]
Hi, i can work automating the translation process. Could i get this issue assigned to me?

**Comment by Raff-dev** [comment]
> Hi, i can work automating the translation process. Could i get this issue assigned to me?

Can you share your thoughts on What would be your plan of addressing this issue? Will you use openai GPT or deepl or google translate?

**Comment by ManindraDeMel** [comment]
> automating

Theres a free tool called argos translate.

Heres an example of a workflow

```yaml
name: Translate README

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Argos Translate
      run: |
        pip install argos-translate

    - name: Translate README to Spanish (as an example)
      run: |
        argos-translate-translate --from-lang en --to-lang es README.md README_es.md

    - name: Commit translated README
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README_es.md
        git commit -m "Added Spanish translation for README" || echo "No changes to commit"
        git push
```
